import { Router } from 'express';
import { prisma } from '../../lib/db.js';
import { requireAuth } from '../../lib/auth.js';
import { bus } from '../../events/bus.js';

export const healthRouter = Router();

// Simple threshold rules per §6.3 — flags route to Care Manager, never shown to parent as "advice".
const THRESHOLDS = {
  bp: { check: (v) => { const [sys] = v.split('/').map(Number); return sys >= 160 || sys <= 90; } },
  sugar: { check: (v) => Number(v) >= 200 || Number(v) <= 70 },
  spo2: { check: (v) => Number(v) < 92 },
  pulse: { check: (v) => Number(v) > 120 || Number(v) < 50 },
};

// POST /v1/parents/:id/vitals — record reading (caregiver/device)
healthRouter.post('/parents/:id/vitals', requireAuth, async (req, res) => {
  const { type, value, unit, visitId, source = 'caregiver' } = req.body;
  if (!type || value == null || !unit) {
    return res.status(400).json({ error: 'type, value, unit required' });
  }

  const rule = THRESHOLDS[type];
  const flagged = rule ? Boolean(rule.check(String(value))) : false;

  const reading = await prisma.vitalsReading.create({
    data: { parentId: req.params.id, visitId, type, value: String(value), unit, source, flagged },
  });

  await bus.emitEvent('vitals.recorded', { parentId: req.params.id, type, value, flagged });

  if (flagged) {
    await prisma.alert.create({
      data: {
        parentId: req.params.id,
        severity: 'warning',
        type: 'vitals_out_of_range',
      },
    });
  }

  res.status(201).json(reading);
});

// GET /v1/parents/:id/vitals?type=bp&range=30d — trend
healthRouter.get('/parents/:id/vitals', requireAuth, async (req, res) => {
  const { type, range } = req.query;
  const where = { parentId: req.params.id };
  if (type) where.type = type;
  if (range) {
    const days = parseInt(range.replace('d', ''), 10) || 30;
    where.recordedAt = { gte: new Date(Date.now() - days * 86400000) };
  }
  const readings = await prisma.vitalsReading.findMany({ where, orderBy: { recordedAt: 'asc' } });
  res.json(readings);
});

// POST /v1/parents/:id/medication-schedules — set up once, fires forever.
// "Amlodipine, daily at 08:00 and 20:00" — the scheduler (src/scheduler/medication.js)
// auto-generates each day's reminder and rings the alarm; nobody re-enters this daily.
healthRouter.post('/parents/:id/medication-schedules', requireAuth, async (req, res) => {
  const { medication, timesOfDay, gracePeriodMinutes = 15 } = req.body;
  if (!medication || !Array.isArray(timesOfDay) || timesOfDay.length === 0) {
    return res.status(400).json({ error: 'medication, timesOfDay (array of "HH:MM") required' });
  }
  const schedule = await prisma.medicationSchedule.create({
    data: { parentId: req.params.id, medication, timesOfDayJson: JSON.stringify(timesOfDay), gracePeriodMinutes },
  });
  res.status(201).json(schedule);
});

// GET /v1/parents/:id/medication-schedules — list recurring schedules
healthRouter.get('/parents/:id/medication-schedules', requireAuth, async (req, res) => {
  const schedules = await prisma.medicationSchedule.findMany({
    where: { parentId: req.params.id },
    orderBy: { createdAt: 'desc' },
  });
  res.json(schedules);
});

// PATCH /v1/medication-schedules/:id — pause/resume a recurring reminder
healthRouter.patch('/medication-schedules/:id', requireAuth, async (req, res) => {
  const { active } = req.body;
  const schedule = await prisma.medicationSchedule.update({
    where: { id: req.params.id },
    data: { active: Boolean(active) },
  });
  res.json(schedule);
});

// GET /v1/parents/:id/medications — adherence log (auto-generated by the scheduler,
// plus any manual one-off entries)
healthRouter.get('/parents/:id/medications', requireAuth, async (req, res) => {
  const logs = await prisma.medicationLog.findMany({
    where: { parentId: req.params.id },
    orderBy: { scheduledAt: 'desc' },
  });
  res.json(logs);
});

// PATCH /v1/medications/:id — caregiver marks a dose given or missed; missed raises an alert
healthRouter.patch('/medications/:id', requireAuth, async (req, res) => {
  const { status } = req.body;
  if (!['given', 'missed'].includes(status)) return res.status(400).json({ error: 'status must be given|missed' });

  const log = await prisma.medicationLog.update({
    where: { id: req.params.id },
    data: { status, givenAt: status === 'given' ? new Date() : null, recordedBy: req.user.id },
  });

  if (status === 'missed') {
    await bus.emitEvent('medication.missed', { parentId: log.parentId, medication: log.medication });
    await prisma.alert.create({
      data: { parentId: log.parentId, severity: 'warning', type: 'med_missed' },
    });
  }

  res.json(log);
});
